"""Tests for the v0.4 local annotation tool (app/annotation_tool). Uses a
small synthetic manifest -- the real 20-plan manifest is generated by
scripts/run_v04_pipeline.py and is not part of the committed test fixtures
(crops/manifest for the real plans are pseudonymous but still real customer
plan content; the annotation tool's own correctness doesn't need them).
"""
from __future__ import annotations

import importlib
import json
import os

import cv2
import numpy as np
import pymupdf
import pytest
from fastapi.testclient import TestClient


@pytest.fixture()
def client(tmp_path, monkeypatch):
    crops_dir = tmp_path / "crops"
    crops_dir.mkdir()
    img = np.full((80, 80, 3), 255, dtype="uint8")
    cv2.imwrite(str(crops_dir / "AC001.png"), img)
    cv2.imwrite(str(crops_dir / "AC002.png"), img)

    manifest = [
        {
            "candidate_id": "AC001", "plan_id_pseudonymous": "DEV-01", "style_family": "STANDALONE-1",
            "split": "train", "page": 1, "crop_path": str(crops_dir / "AC001.png"),
            "bbox_page_space": [10, 10, 20, 20], "crop_bbox_page_space": [0, 0, 80, 80],
            "bbox_in_crop_px": [30, 30, 50, 50], "corrected_bbox_in_crop_px": None,
            "class": None, "verification_status": "UNLABELED",
            "graph_association": {"relation": "on_edge", "node_ids": [], "edge_ids": ["e1"]},
            "engine_suggestions": {"plan_specific": {"label": "Ventil", "score": 0.9}, "generic": None},
            "annotator_note": None,
        },
        {
            "candidate_id": "AC002", "plan_id_pseudonymous": "DEV-01", "style_family": "STANDALONE-1",
            "split": "train", "page": 1, "crop_path": str(crops_dir / "AC002.png"),
            "bbox_page_space": [50, 50, 60, 60], "crop_bbox_page_space": [0, 0, 80, 80],
            "bbox_in_crop_px": [10, 10, 30, 30], "corrected_bbox_in_crop_px": None,
            "class": None, "verification_status": "UNLABELED",
            "graph_association": {"relation": "near_not_connected", "node_ids": [], "edge_ids": []},
            "engine_suggestions": {"plan_specific": None, "generic": None},
            "annotator_note": None,
        },
    ]
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
    classes_path = tmp_path / "classes.json"
    classes_path.write_text(json.dumps({"Ventil": 0, "Pumpe": 1, "NOT_A_COMPONENT": 2, "AMBIGUOUS": 3}), encoding="utf-8")

    monkeypatch.setenv("V04_MANIFEST_PATH", str(manifest_path))
    monkeypatch.setenv("V04_CLASSES_PATH", str(classes_path))
    monkeypatch.setenv("V04_RAW_PLANS_DIR", str(tmp_path))

    import app.annotation_tool.main as main_module
    importlib.reload(main_module)
    return TestClient(main_module.app)


def test_index_page_serves(client):
    r = client.get("/")
    assert r.status_code == 200
    assert "Annotation" in r.text


def test_classes_endpoint(client):
    r = client.get("/api/classes")
    assert r.json() == {"Ventil": 0, "Pumpe": 1, "NOT_A_COMPONENT": 2, "AMBIGUOUS": 3}


def test_progress_starts_at_zero_annotated(client):
    r = client.get("/api/progress")
    assert r.json() == {"annotated": 0, "total": 2, "by_status": {"UNLABELED": 2}}


def test_candidate_detail_carries_suggestions_and_graph_relation(client):
    r = client.get("/api/candidate/AC001")
    body = r.json()
    assert body["engine_suggestions"]["plan_specific"]["label"] == "Ventil"
    assert body["graph_association"]["relation"] == "on_edge"


def test_unknown_candidate_is_404(client):
    assert client.get("/api/candidate/DOES_NOT_EXIST").status_code == 404


def test_crop_image_is_served(client):
    r = client.get("/api/candidate/AC001/crop")
    assert r.status_code == 200
    assert r.headers["content-type"] == "image/png"


def test_annotate_requires_a_class_when_labeling(client):
    r = client.post("/api/candidate/AC001/annotate", json={"status": "LABELED"})
    assert r.status_code == 400


def test_annotate_persists_and_updates_progress(client):
    r = client.post("/api/candidate/AC001/annotate", json={"assigned_class": "Ventil", "status": "LABELED"})
    assert r.status_code == 200
    assert r.json()["verification_status"] == "LABELED"
    progress = client.get("/api/progress").json()
    assert progress["annotated"] == 1


def test_skip_does_not_require_a_class(client):
    r = client.post("/api/candidate/AC002/annotate", json={"status": "SKIPPED"})
    assert r.status_code == 200
    assert r.json()["verification_status"] == "SKIPPED"


def test_annotation_survives_a_fresh_store_reload(client, monkeypatch):
    client.post("/api/candidate/AC001/annotate", json={"assigned_class": "Pumpe", "status": "LABELED"})
    import app.annotation_tool.main as main_module
    main_module._store = None  # force a fresh read from disk, like a server restart would
    r = client.get("/api/candidate/AC001")
    assert r.json()["class"] == "Pumpe"
    assert r.json()["verification_status"] == "LABELED"


# ---- wide-context view's own mandatory PII safety net (regression test for
# the same real finding candidates.py's tests cover: this endpoint renders a
# BIGGER, live region the offline pipeline never checked at all) ----

def _make_plan_pdf(path, text, text_pos=(50, 50)):
    doc = pymupdf.open()
    page = doc.new_page(width=400, height=400)
    page.insert_text(text_pos, text, fontsize=10)
    doc.save(path)
    doc.close()


def test_wide_crop_is_served_when_the_region_has_no_pii(client, tmp_path):
    _make_plan_pdf(os.path.join(str(tmp_path), "DEV-01.pdf"), "PE-S 63 Bad/WC 03_101_09", text_pos=(15, 15))
    r = client.get("/api/candidate/AC001/wide_crop")
    assert r.status_code == 200
    assert r.headers["content-type"] == "image/png"


def test_wide_crop_is_withheld_when_the_region_overlaps_title_block_text(client, tmp_path):
    # Short enough that the whole postal-code+town match actually survives
    # being clipped to the small wide-context region this candidate's tiny
    # bbox produces in this test (a real title block's PII spans far more
    # area than any single candidate's context window, as found on the real
    # plan this check was added for -- this synthetic case just needs ONE
    # fully-contained match to prove the endpoint checks at all).
    _make_plan_pdf(os.path.join(str(tmp_path), "DEV-01.pdf"), "8001 Zuerich AG", text_pos=(5, 15))
    r = client.get("/api/candidate/AC001/wide_crop")
    assert r.status_code == 403
